# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

image: python:3.10.4

include:
- template: Security/SAST.gitlab-ci.yml

stages:
  - lint
  - test
  - build
  - publish
  - release

before_script:
    - export POETRY_HOME=/opt/poetry
    - python3 -m venv $POETRY_HOME
    - make install

lint:
  stage: lint
  script: |
    pip install black
    make lint

sast:
  stage: test

test:
  stage: test
  needs:
    - lint
  script: make test