# ref https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
image: python:3.10.4

definitions:
  caches:
    venv: .venv

pipelines:
  default:
    - step:
        caches:
          - venv
        script:
          - export POETRY_HOME=/opt/poetry
          - python3 -m venv $POETRY_HOME
          - make install

    - step:
        name: Lint
        script:
          - pip install black
          - make lint

    - step:
        name: Tests
        script:
          - pip install pytest
          - pip install pytest-cov
          - make test

    - step:
        name: Build
        script:
          - pip install poetry
          - make build

  pull-requests:
    '**':
      - step:
          caches:
            - venv

          script:
            - export POETRY_HOME=/opt/poetry
            - python3 -m venv $POETRY_HOME
            - make install

      - step:
          name: Lint
          script:
            - pip install black
            - make lint

      - step:
          name: Tests
          script:
            - pip install pytest
            - pip install pytest-cov
            - make test

      - step:
          name: Build
          script:
            - make build
