name: Lint Scan Test Build

on: [push, pull_request]

jobs:
  lint-scan-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Restore Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.venv
          key: ${{ runner.os }}-pyproject-${{ hashFiles('tictacai/pyproject.toml') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'      
        run: make install

      - name: Lint application
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make build
