name: PyPI Upload

on:
  push:
    branches: [main]

jobs:
  build:
    name: PyPI Upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install latest pip, build, twine
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install --upgrade build twine
          pip install poetry

      - name: Build wheel and source distributions
        run: make build

      - name: Upload to PyPI via Twine
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          cd tictacai
          twine upload --verbose -u '__token__' dist/*
